// Seed list of real species: [common name, scientific name, kind].
// The fetch script enriches each with a summary and image from Wikipedia.
export const SEED = [
  // Broadleaf & flowering trees
  ["English Oak", "Quercus robur", "tree"],
  ["Sessile Oak", "Quercus petraea", "tree"],
  ["Cork Oak", "Quercus suber", "tree"],
  ["Red Maple", "Acer rubrum", "tree"],
  ["Sugar Maple", "Acer saccharum", "tree"],
  ["Japanese Maple", "Acer palmatum", "tree"],
  ["Norway Maple", "Acer platanoides", "tree"],
  ["Silver Birch", "Betula pendula", "tree"],
  ["Paper Birch", "Betula papyrifera", "tree"],
  ["European Beech", "Fagus sylvatica", "tree"],
  ["American Beech", "Fagus grandifolia", "tree"],
  ["Horse Chestnut", "Aesculus hippocastanum", "tree"],
  ["Sweet Chestnut", "Castanea sativa", "tree"],
  ["Common Ash", "Fraxinus excelsior", "tree"],
  ["European Hornbeam", "Carpinus betulus", "tree"],
  ["Small-leaved Lime", "Tilia cordata", "tree"],
  ["London Plane", "Platanus x acerifolia", "tree"],
  ["American Sycamore", "Platanus occidentalis", "tree"],
  ["Weeping Willow", "Salix babylonica", "tree"],
  ["White Willow", "Salix alba", "tree"],
  ["Quaking Aspen", "Populus tremuloides", "tree"],
  ["Black Poplar", "Populus nigra", "tree"],
  ["Eastern Cottonwood", "Populus deltoides", "tree"],
  ["Common Hawthorn", "Crataegus monogyna", "tree"],
  ["Rowan", "Sorbus aucuparia", "tree"],
  ["Tulip Tree", "Liriodendron tulipifera", "tree"],
  ["Southern Magnolia", "Magnolia grandiflora", "tree"],
  ["Black Walnut", "Juglans nigra", "tree"],
  ["English Walnut", "Juglans regia", "tree"],
  ["Pecan", "Carya illinoinensis", "tree"],
  ["Honey Locust", "Gleditsia triacanthos", "tree"],
  ["Black Locust", "Robinia pseudoacacia", "tree"],
  ["Jacaranda", "Jacaranda mimosifolia", "tree"],
  ["Royal Poinciana", "Delonix regia", "tree"],
  ["Baobab", "Adansonia digitata", "tree"],
  ["Banyan", "Ficus benghalensis", "tree"],
  ["Sacred Fig", "Ficus religiosa", "tree"],
  ["Neem", "Azadirachta indica", "tree"],
  ["Teak", "Tectona grandis", "tree"],
  ["Mahogany", "Swietenia mahagoni", "tree"],
  ["Blue Gum", "Eucalyptus globulus", "tree"],
  ["Rainbow Eucalyptus", "Eucalyptus deglupta", "tree"],
  ["Ginkgo", "Ginkgo biloba", "tree"],
  ["Japanese Cherry", "Prunus serrulata", "tree"],
  ["Eastern Redbud", "Cercis canadensis", "tree"],
  ["Flowering Dogwood", "Cornus florida", "tree"],
  ["Sweetgum", "Liquidambar styraciflua", "tree"],
  ["American Elm", "Ulmus americana", "tree"],
  ["Common Alder", "Alnus glutinosa", "tree"],
  ["Hazel", "Corylus avellana", "tree"],
  ["Olive", "Olea europaea", "tree"],
  ["Silver Wattle", "Acacia dealbata", "tree"],
  ["Tamarind", "Tamarindus indica", "tree"],
  ["Moringa", "Moringa oleifera", "tree"],
  ["Dragon's Blood Tree", "Dracaena cinnabari", "tree"],
  ["Joshua Tree", "Yucca brevifolia", "tree"],

  // Conifers
  ["Scots Pine", "Pinus sylvestris", "conifer"],
  ["Eastern White Pine", "Pinus strobus", "conifer"],
  ["Stone Pine", "Pinus pinea", "conifer"],
  ["Norway Spruce", "Picea abies", "conifer"],
  ["Blue Spruce", "Picea pungens", "conifer"],
  ["Douglas Fir", "Pseudotsuga menziesii", "conifer"],
  ["Silver Fir", "Abies alba", "conifer"],
  ["Balsam Fir", "Abies balsamea", "conifer"],
  ["European Larch", "Larix decidua", "conifer"],
  ["Coast Redwood", "Sequoia sempervirens", "conifer"],
  ["Giant Sequoia", "Sequoiadendron giganteum", "conifer"],
  ["Dawn Redwood", "Metasequoia glyptostroboides", "conifer"],
  ["Bald Cypress", "Taxodium distichum", "conifer"],
  ["Western Red Cedar", "Thuja plicata", "conifer"],
  ["Common Juniper", "Juniperus communis", "conifer"],
  ["English Yew", "Taxus baccata", "conifer"],
  ["Monkey Puzzle", "Araucaria araucana", "conifer"],
  ["Norfolk Island Pine", "Araucaria heterophylla", "conifer"],
  ["Wollemi Pine", "Wollemia nobilis", "conifer"],
  ["Cedar of Lebanon", "Cedrus libani", "conifer"],
  ["Italian Cypress", "Cupressus sempervirens", "conifer"],

  // Fruits & fruit trees
  ["Apple", "Malus domestica", "fruit"],
  ["Pear", "Pyrus communis", "fruit"],
  ["Sweet Cherry", "Prunus avium", "fruit"],
  ["Peach", "Prunus persica", "fruit"],
  ["Apricot", "Prunus armeniaca", "fruit"],
  ["Plum", "Prunus domestica", "fruit"],
  ["Almond", "Prunus dulcis", "fruit"],
  ["Common Fig", "Ficus carica", "fruit"],
  ["Pomegranate", "Punica granatum", "fruit"],
  ["Lemon", "Citrus limon", "fruit"],
  ["Orange", "Citrus sinensis", "fruit"],
  ["Lime", "Citrus aurantiifolia", "fruit"],
  ["Grapefruit", "Citrus paradisi", "fruit"],
  ["Mango", "Mangifera indica", "fruit"],
  ["Avocado", "Persea americana", "fruit"],
  ["Banana", "Musa acuminata", "fruit"],
  ["Papaya", "Carica papaya", "fruit"],
  ["Guava", "Psidium guajava", "fruit"],
  ["Lychee", "Litchi chinensis", "fruit"],
  ["Persimmon", "Diospyros kaki", "fruit"],
  ["Jackfruit", "Artocarpus heterophyllus", "fruit"],
  ["Durian", "Durio zibethinus", "fruit"],
  ["Pineapple", "Ananas comosus", "fruit"],
  ["Blueberry", "Vaccinium corymbosum", "fruit"],
  ["Cranberry", "Vaccinium macrocarpon", "fruit"],
  ["Raspberry", "Rubus idaeus", "fruit"],
  ["Blackberry", "Rubus fruticosus", "fruit"],
  ["Strawberry", "Fragaria x ananassa", "fruit"],
  ["Watermelon", "Citrullus lanatus", "fruit"],

  // Vegetables
  ["Tomato", "Solanum lycopersicum", "vegetable"],
  ["Potato", "Solanum tuberosum", "vegetable"],
  ["Eggplant", "Solanum melongena", "vegetable"],
  ["Carrot", "Daucus carota", "vegetable"],
  ["Onion", "Allium cepa", "vegetable"],
  ["Garlic", "Allium sativum", "vegetable"],
  ["Leek", "Allium ampeloprasum", "vegetable"],
  ["Cabbage", "Brassica oleracea", "vegetable"],
  ["Broccoli", "Brassica oleracea var. italica", "vegetable"],
  ["Cauliflower", "Brassica oleracea var. botrytis", "vegetable"],
  ["Kale", "Brassica oleracea var. sabellica", "vegetable"],
  ["Spinach", "Spinacia oleracea", "vegetable"],
  ["Lettuce", "Lactuca sativa", "vegetable"],
  ["Cucumber", "Cucumis sativus", "vegetable"],
  ["Pumpkin", "Cucurbita pepo", "vegetable"],
  ["Bell Pepper", "Capsicum annuum", "vegetable"],
  ["Chili Pepper", "Capsicum frutescens", "vegetable"],
  ["Pea", "Pisum sativum", "vegetable"],
  ["Common Bean", "Phaseolus vulgaris", "vegetable"],
  ["Sweet Corn", "Zea mays", "vegetable"],
  ["Beetroot", "Beta vulgaris", "vegetable"],
  ["Radish", "Raphanus sativus", "vegetable"],
  ["Celery", "Apium graveolens", "vegetable"],
  ["Asparagus", "Asparagus officinalis", "vegetable"],
  ["Sweet Potato", "Ipomoea batatas", "vegetable"],
  ["Okra", "Abelmoschus esculentus", "vegetable"],
  ["Rhubarb", "Rheum rhabarbarum", "vegetable"],

  // Herbs & spices
  ["Basil", "Ocimum basilicum", "herb"],
  ["Spearmint", "Mentha spicata", "herb"],
  ["Rosemary", "Salvia rosmarinus", "herb"],
  ["Thyme", "Thymus vulgaris", "herb"],
  ["Oregano", "Origanum vulgare", "herb"],
  ["Sage", "Salvia officinalis", "herb"],
  ["Parsley", "Petroselinum crispum", "herb"],
  ["Coriander", "Coriandrum sativum", "herb"],
  ["Dill", "Anethum graveolens", "herb"],
  ["Chives", "Allium schoenoprasum", "herb"],
  ["Chamomile", "Matricaria chamomilla", "herb"],
  ["Ginger", "Zingiber officinale", "herb"],
  ["Turmeric", "Curcuma longa", "herb"],
  ["Lemongrass", "Cymbopogon citratus", "herb"],

  // Flowers
  ["China Rose", "Rosa chinensis", "flower"],
  ["Sunflower", "Helianthus annuus", "flower"],
  ["Tulip", "Tulipa gesneriana", "flower"],
  ["Wild Daffodil", "Narcissus pseudonarcissus", "flower"],
  ["Common Daisy", "Bellis perennis", "flower"],
  ["Mexican Marigold", "Tagetes erecta", "flower"],
  ["Common Poppy", "Papaver rhoeas", "flower"],
  ["English Lavender", "Lavandula angustifolia", "flower"],
  ["Madonna Lily", "Lilium candidum", "flower"],
  ["Bearded Iris", "Iris germanica", "flower"],
  ["Chinese Peony", "Paeonia lactiflora", "flower"],
  ["Florist's Chrysanthemum", "Chrysanthemum morifolium", "flower"],
  ["Carnation", "Dianthus caryophyllus", "flower"],
  ["Geranium", "Pelargonium hortorum", "flower"],
  ["Snapdragon", "Antirrhinum majus", "flower"],
  ["Common Foxglove", "Digitalis purpurea", "flower"],
  ["Bluebell", "Hyacinthoides non-scripta", "flower"],
  ["Saffron Crocus", "Crocus sativus", "flower"],
  ["Bird of Paradise", "Strelitzia reginae", "flower"],
  ["Wood Forget-me-not", "Myosotis sylvatica", "flower"],
  ["Wild Pansy", "Viola tricolor", "flower"],
  ["Moth Orchid", "Phalaenopsis amabilis", "flower"],
  ["Lily of the Valley", "Convallaria majalis", "flower"],

  // Shrubs (incl. notable toxic)
  ["Hydrangea", "Hydrangea macrophylla", "shrub"],
  ["Chinese Hibiscus", "Hibiscus rosa-sinensis", "shrub"],
  ["Common Holly", "Ilex aquifolium", "shrub"],
  ["Rhododendron", "Rhododendron ponticum", "shrub"],
  ["Common Lilac", "Syringa vulgaris", "shrub"],
  ["Butterfly Bush", "Buddleja davidii", "shrub"],
  ["Oleander", "Nerium oleander", "shrub"],
  ["Deadly Nightshade", "Atropa belladonna", "shrub"],
  ["Castor Bean", "Ricinus communis", "shrub"],
  ["Hemlock", "Conium maculatum", "herb"],
  ["Monkshood", "Aconitum napellus", "flower"],
  ["Stinging Nettle", "Urtica dioica", "herb"],
  ["Giant Hogweed", "Heracleum mantegazzianum", "herb"],

  // Ferns
  ["Lady Fern", "Athyrium filix-femina", "fern"],
  ["Bracken", "Pteridium aquilinum", "fern"],
  ["Maidenhair Fern", "Adiantum capillus-veneris", "fern"],
  ["Boston Fern", "Nephrolepis exaltata", "fern"],
  ["Hart's-tongue Fern", "Asplenium scolopendrium", "fern"],
  ["Ostrich Fern", "Matteuccia struthiopteris", "fern"],
  ["Royal Fern", "Osmunda regalis", "fern"],

  // Palms
  ["Coconut Palm", "Cocos nucifera", "palm"],
  ["Date Palm", "Phoenix dactylifera", "palm"],
  ["Areca Palm", "Dypsis lutescens", "palm"],
  ["Oil Palm", "Elaeis guineensis", "palm"],

  // Succulents & cacti
  ["Aloe Vera", "Aloe vera", "succulent"],
  ["Saguaro Cactus", "Carnegiea gigantea", "succulent"],
  ["Prickly Pear", "Opuntia ficus-indica", "succulent"],
  ["Century Plant", "Agave americana", "succulent"],
  ["Jade Plant", "Crassula ovata", "succulent"],
  ["Christmas Cactus", "Schlumbergera truncata", "succulent"],
  ["Common Echeveria", "Echeveria elegans", "succulent"],

  // Grasses & bamboo
  ["Moso Bamboo", "Phyllostachys edulis", "grass"],
  ["Sugarcane", "Saccharum officinarum", "grass"],
  ["Bread Wheat", "Triticum aestivum", "grass"],
  ["Rice", "Oryza sativa", "grass"],
  ["Barley", "Hordeum vulgare", "grass"],
  ["Oat", "Avena sativa", "grass"],
  ["Pampas Grass", "Cortaderia selloana", "grass"],
  ["Common Reed", "Phragmites australis", "grass"],

  // Climbers
  ["Grape Vine", "Vitis vinifera", "climber"],
  ["Kiwifruit", "Actinidia deliciosa", "climber"],
  ["Common Ivy", "Hedera helix", "climber"],
  ["Chinese Wisteria", "Wisteria sinensis", "climber"],
  ["Morning Glory", "Ipomoea purpurea", "climber"],
  ["Passionfruit", "Passiflora edulis", "climber"],
  ["Traveller's Joy", "Clematis vitalba", "climber"],
  ["Common Hop", "Humulus lupulus", "climber"],
  ["Poison Ivy", "Toxicodendron radicans", "climber"],

  // Aquatic
  ["Sacred Lotus", "Nelumbo nucifera", "aquatic"],
  ["White Water Lily", "Nymphaea alba", "aquatic"],
  ["Papyrus", "Cyperus papyrus", "aquatic"],

  // Houseplants
  ["Swiss Cheese Plant", "Monstera deliciosa", "houseplant"],
  ["Golden Pothos", "Epipremnum aureum", "houseplant"],
  ["Peace Lily", "Spathiphyllum wallisii", "houseplant"],
  ["Spider Plant", "Chlorophytum comosum", "houseplant"],
  ["Rubber Plant", "Ficus elastica", "houseplant"],
  ["ZZ Plant", "Zamioculcas zamiifolia", "houseplant"],
  ["Fiddle-leaf Fig", "Ficus lyrata", "houseplant"],
  ["Snake Plant", "Dracaena trifasciata", "houseplant"],
  ["Heartleaf Philodendron", "Philodendron hederaceum", "houseplant"],
  ["Weeping Fig", "Ficus benjamina", "houseplant"],
];
